# Site settings
baseURL = "https://www.gabrielemarchesan.com/"
languageCode = "en-US"
title = "Gabriele Marchesan's Personal Frontpage on the web"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2020 Gabriele Marchesan"

[params]

  # Metadata for search engines and social sharing
  author = "Gabriele Marchesan"
  description = "Gabriele Marchesan's personal frontpage in the web. Personal experinces in self-improving and digital wellbeing."
  shareImage = "images/social.jpg"
  twitterHandle = "gabrielemarchesan"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background.jpg"
      position = "center right"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      #[[params.links.list1.link]]
      #  text = "Blog"
      #  url = "#"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:gabriele.marchesan@outlook.it"

      #[[params.links.list1.link]]
      #  text = "Newsletter"
      #  url = "#"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      #[[params.links.list2.link]]
      #  text = "Twitter"
      #  url = "#"

      [[params.links.list2.link]]
        text = "Instagram"
        url = "https://www.instagram.com/gabriele_marchesan/"

      #[[params.links.list2.link]]
      #  text = "Dribbble"
      #  url = "#"

  # Links List #3
  #[[params.links]]
  #  [params.links.list3]
  #    heading = "Network"

  #    [[params.links.list3.link]]
  #      text = "Link One"
  #      url = "#"

  #    [[params.links.list3.link]]
  #      text = "Link Two"
  #      url = "#"

  #    [[params.links.list3.link]]
  #      text = "Link Three"
  #      url = "#"
